{
 "title": "Wikimedia Recent Changes",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Changes Over Time (WIP)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "default",
     "rawSql": "SELECT \r\n  to_timestamp(time) as time, \r\n  change_type, \r\n  count as number\r\nFROM wikimedia.main_marts.mart_changes_over_time \r\n"
    }
   ]
  },
  {
   "title": "Total Top 10 Most Changed Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "default",
     "rawSql": "SELECT title as Title, edit_count as Count FROM wikimedia.main_marts.mart_top_10_pages LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Bot Edit Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "default",
     "rawSql": "SELECT (1 - bot_edits/(human_edits + bot_edits)) as \"Human Ratio\" FROM wikimedia.main_marts.mart_user_bot_ratio"
    }
   ]
  },
  {
   "title": "Total Top 10 Most Active Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "dataset": "default",
     "rawSql": "SELECT username as User, edit_count as Count FROM wikimedia.main_marts.mart_top_10_users LIMIT 50 "
    }
   ]
  }
 ]
}